###
GET http://localhost:8080/api/user/all HTTP/1.1

###
POST http://localhost:8080/api/user/persona HTTP/1.1
Content-Type: application/json

{
  "dni": "12345678",
  "primerApellido": "Perez",
  "segundoApellido": "Perez",
  "prenombre": "Juan"
}


### Transportista 78943713 Gerente 77688137
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "dni": "78943713"
}

### MODULO DE PEDIDOS ###

###
GET http://localhost:8080/api/pedido/all HTTP/1.1

###
POST http://localhost:8080/api/pedido/datos HTTP/1.1
Content-Type: application/json

{
  "personaRequest": {
    "idEstadoCivil": 1,
    "idNacionalidad": 1,
    "idGenero": 1,
    "dni": "12345678",
    "primerApellido": "Perez",
    "segundoApellido": "Perez",
    "prenombre": "Juan"
  },
  "clienteRequest": {
    "idCliente": 1,
    "nombre": "Juan Perez",
    "ruc": "12345678",
    "direccion": "Direccion de prueba"
  },
  "representanteRequest": {
    "telefono": "12345678",
    "correoEmpresarial": "correo@correo.com",
    "cargo": "Cargo de prueba"
  }
}

###
GET http://localhost:8080/api/pedido/productos HTTP/1.1

###
POST http://localhost:8080/api/pedido/ticket HTTP/1.1
Content-Type: application/json

{
  "fechaEntrega": "2024-01-01"
}

###
POST http://localhost:8080/api/pedido/new HTTP/1.1
Content-Type: application/json

{
  "idRepresentante": 1,
  "idEmpleadoRegistro": 1,
  "idTipoPedido": "V",
  "idEstadoPedido": "A",
  "fechaRegistro": "2024-01-01",
  "fechaEntrega": "2024-01-20",
  "pedidoTicketProductoRequest": [
    {
      "idElementoCatalogo": 1,
      "cantidad": 1
    },
    {
      "idElementoCatalogo": 2,
      "cantidad": 2
    }
  ]
}

### MODULO DE REPORTES ###

GET http://localhost:8080/api/reportes/operacion HTTP/1.1

###
POST http://localhost:8080/api/reportes/programacion HTTP/1.1
Content-Type: application/json

{
  "idRepresentante": 1,
  "idReporteFormato": 1,
  "idReporteEstado": 1,
  "idReporteFrecuencia": 1,
  "fechaInicio": "2024-01-01",
  "fechaFin": "2024-01-20"
} 
